const cateBar = [
  {
    cateName: "全部",
    isClick: false,
    svg: "",
  },
  {
    cateName: "網頁設計",
    isClick: false,
    svg: "",
  },
  {
    cateName: "切版臨摹",
    isClick: true,
    svg: "",
  },
  {
    cateName: "功能實作",
    isClick: false,
    svg: "",
  },
  {
    cateName: "平面設計",
    isClick: false,
    svg: "",
  },
];

const data = [
  {
    id: "5",
    picture: require("@/assets/img/view-curry.png"),
    title: "咖哩大食記",
    info: "嘗試將平常的口袋名單做一個表單練習",
    infoDetail:
      "目前還在測試中。<br/>我是個咖哩魔人，平常就有將想吃的店存起來的習慣，希望有朝一日可以寫出自己的口袋名單整理網站。",
    color: ["#eceee7","#ebbe94cc", "#d49696", "#fff5dd", "#be1c1c"],
    colorInfo: "使用降低彩度後的咖哩相關色系作搭配。",
    cats: ["全部", "功能實作"],
    show: true,
    design: "無",
    font: "無",
    end: "無",
    package: "無",
    link: "https://apo0717.github.io/curry/",
  },
  {
    id: "4",
    picture: require("@/assets/img/view-lunarPhase.png"),
    title: "Lunar Phase",
    info: "模擬出一個原創品牌女性生理用品資訊站。",
    infoDetail:
      "專題協作作品<br/>以女性為主客群的生理用品資訊站。<br/><br/>推廣能重複使用的新式生理用品，更延伸至心靈層面的陪伴與關照，透過文章專欄、活動講座推廣等，與使用者一同創造更多美好的生活體驗。<br/>我負責月訂制(KIT)區塊 ＆ 心理測驗，以客製化功能增加顧客黏著度。根據使用者不同的生理用品使用需求，自由組合產品禮包，並於每個月固定日期寄出，也可隨時終止契約並退回部分費用。",
    color: ["#f7f7ee", "#fdd2bb", "#383844", "#ffffff", "#e64b4b"],
    colorInfo:
      "主視覺色系使用較為平靜清淡的色彩配置，降低主色調彩度，以月亮出現時天空的色彩為靈感。",
    cats: ["全部", "網頁設計"],
    show: true,
    design: "PhotoShop / Illustrator / AdobeXD",
    font: "React / SCSS / Bootstrap4",
    end: "Node.js / MySQL",
    package: "AOS / SweetAlert",
    link: false,
  },
  {
    id: "3",
    picture: require("@/assets/img/view-lkk.png"),
    title: "當我們老在一起",
    info: "切版練習。",
    infoDetail: "切版練習，參考新北市老人健保照護資訊網站",
    color: false,
    colorInfo: false,
    cats: ["全部", "切版臨摹"],
    show: true,
    design: "無",
    font: "HTML5 / CSS3",
    end: "無",
    package: "無",
    link: "https://apo0717.github.io/psdToHtml-Lkk/public/indexLkk",
  },

  {
    id: "2",
    picture: require("@/assets/img/view-ps.png"),
    title: "PlayStation",
    info: "初次切版練習。",
    infoDetail:
      "初次切版練習，參考PlayStation官方網站。<br/>當時發行的主打是惡靈古堡8，有點想玩但是我打不準。",
    color: false,
    colorInfo: false,
    cats: ["全部", "切版臨摹"],
    show: true,
    design: "無",
    font: "HTML5 / CSS3",
    end: "無",
    package: "無",
    link: "https://apo0717.github.io/psdToHtml-PlayStation/",
  },
  {
    id: "1",
    picture: require("@/assets/img/view-design.png"),
    title: "平面設計整合",
    info: "過去的平面設計粗略整理",
    infoDetail: "目前都先統一放在這",
    color: false,
    colorInfo: false,
    cats: ["全部", "平面設計"],
    show: true,
    design: "PhotoShop / Illustrator / CSP / 手繪",
    font: "無",
    end: "無",
    package: "無",
    link: "https://docs.google.com/presentation/d/1ATv1xodASMXwrVJwag90RyD-zUNqtl7J8vllT8MWxNE/edit#slide=id.g2d4f0d26ed_0_0",
  },
];

export default { data, cateBar };
